apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-0e73167119d54c68e
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-061d3117868d3d89d
      us-east-1b:
        id: subnet-0add46cdd6be654aa
    private:
      us-east-1a:
        id: subnet-033b3b776cf23fd35
      us-east-1b:
        id: subnet-0e0a44795c5988db6

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 0
    privateNetworking: true
